### ISSUE TITLE
How to use bluegate ?

### ISSUE THREAD

**Issue by galactghost** [ollypwn/BlueGate#3]
I copied bluegate.exe from github and  tried to run it by ./bluegate.exe IP address --mode check but the code is giving me three following errors and line number of the error code   .
1. connection = connection(args.host, args.port) line 130
2.  self.connection = SSL.Connection(SSL.Context(0), self.socket) line 65
3. method_func, version = self._methods[method] line 710

**Comment by jjguz17** [comment]
I got the same error in Kali:

`└─$ python3 BlueGate.py -M check -P 3389 <IP>
Traceback (most recent call last):
  File "/home/kali/Desktop/BlueGate/BlueGate.py", line 130, in <module>
    connection = Connection(args.host, args.port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/BlueGate/BlueGate.py", line 65, in __init__
    self.connection = SSL.Connection(SSL.Context(0), self.socket)
                                     ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 710, in __init__
    method_func, version = self._methods[method]
    ^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable builtin_function_or_method object`

I'm using Python 3.11.5 and I have installed pyOpenSSL

**Comment by jjguz17** [comment]
I was able to run the script by downgrading pyopenssl and cryptography libraries, upgrading them didn't work.

pip uninstall pyopenssl

pip install pyopenssl==22.0.0`

pip uninstall cryptography

pip install cryptography==37.0.0

**Comment by galactghost** [comment]
Thanks

**Comment by galactghost** [comment]
Thanks

**Comment by galactghost** [comment]
![IMG_20231112_231954_884.jpg](https://github.com/ly4k/BlueGate/assets/137290746/7cc104d7-2bc8-4d23-9517-2e5209f924ff)

I am getting this error after uninstalling  and reinstalling and pyopenssl and cryptography

**Comment by galactghost** [comment]
What command did you run to test the code ?

**Comment by galactghost** [comment]
![IMG_20231112_233349_975.jpg](https://github.com/ly4k/BlueGate/assets/137290746/209b90e8-a46a-438c-9ffb-10e31ff09d23)

I tried to run by updating the cryptography and pyopenssl but it give me this error .
